Laboratorio 1

1. Vectores y Matrices

1.1) Contruir un vector para cada estudiantes

```{r}
estudiante_1 <- c(50.4, 62.3, 92.1, 77.6, TRUE)               #1 es igual a TRUE
estudiante_2 <- c(41.7, 87.9, 75.3, 72.4, FALSE)              #0 es igual a FALSE
estudiante_3 <- c(30.3, 67.8, 69.3, 71.2, FALSE)
estudiante_4 <- c(65.4, 85.1, 92.3, 96.8, TRUE)
estudiante_5 <- c(70.4, 88.2, 95.2, 90.7, TRUE)

```

1.2) unificar los vectores creados

```{r}
students_vector <- c(estudiante_1, estudiante_2, estudiante_3, estudiante_4, estudiante_5)
students_vector
```
1.3) crear una matriz

```{r}
students_matrix <- matrix(students_vector, byrow=TRUE, nrow=5)
students_matrix
```
2. Nombramiento de una matriz

2.1) 

```{r}
name_students <- c("Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones", "Tom Hill")
name_courses_legal_age <- c("TIC", "Accounting", "Psychology", "Ethics", "Legal_age")

```
2.2 ) 

```{r}
colnames(students_matrix) <- name_courses_legal_age     #nombre de columnas
rownames(students_matrix) <- name_students              #nombre de filas
students_matrix
```
3. rowSums, cbind

3.1)

```{r}
total_grade_student <- rowSums(students_matrix[c(1:5),c(1:4)])

```
3.2)

```{r}
result_students <- cbind(students_matrix, total_grade_student)
result_students
```

4. Seleccionando elementros de una matriz

4.1) 

```{r}
selected_elements <- result_students[c(1,3,5),c(2,4)]
selected_elements
```
5. Data frames

5.1)

```{r}
students_grades_df <- data.frame(result_students)
students_grades_df
```
5.2)

```{r}
subset(students_grades_df, subset = Accounting > 80 & Legal_age ==TRUE)
```

6. Funciones, Condicionales y Bucles

6.1)

```{r}

students_projection <- function(){
  for(row in 1:nrow(result_students)) {
    for(col in 1:ncol(result_students)) {
        print(result_students[row, col])
    }
  }
}
students_projection

```

6.2)

```{r}

```


7. Data Frames y lapply

7.1

```{r}
index_education <- function(grade){
  (1+(grade/100))/2
}

index_education(100)
```

7.2

```{r}
all_students_grade <- students_grades_df[1:5,1:4]
all_students_grade
```
7.3

```{r}
lapply(all_students_grade, index_education)
```

8. Math utilities

```{r}
score_mean <- colMeans(students_grades_df[1:4])
score_mean
```


